dependencies:
  - name: helloworld-wawa
    version: 0.1.0
    repository: "cm://h.cfcr.io/guptakanigicharla/default/"
  - name: springboot-helloworld
    version: 0.1.0
    repository: "cm://h.cfcr.io/guptakanigicharla/default/"